name: kasir_app_getx
version: 1.0.0+3
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: 1.12.0
  firebase_auth: 3.3.7
  firebase_storage: 10.2.7
  cloud_firestore: 3.1.8
  avatars: 3.0.2
  text_divider: 1.0.0
  path: 1.8.0
  image_picker: 0.8.4+9
  modal_bottom_sheet: 2.0.0
  responsive_framework: 0.1.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

