// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA11naU3K5LBCIaInfWwpFf1j81TC-bxi8',
    appId: '1:453651186731:web:27506043bdef0bf7f1166e',
    messagingSenderId: '453651186731',
    projectId: 'kasir-kafe-app',
    authDomain: 'kasir-kafe-app.firebaseapp.com',
    storageBucket: 'kasir-kafe-app.appspot.com',
    measurementId: 'G-33J62HHQMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAANrITfWR5P1t_XeE37pLjOnbjoDR0Dg8',
    appId: '1:453651186731:android:956f8d9de422410cf1166e',
    messagingSenderId: '453651186731',
    projectId: 'kasir-kafe-app',
    storageBucket: 'kasir-kafe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbW6BF3VBZVWcdJXvD94OJS8O9DBoc43c',
    appId: '1:453651186731:ios:a4871783fa90d4d1f1166e',
    messagingSenderId: '453651186731',
    projectId: 'kasir-kafe-app',
    storageBucket: 'kasir-kafe-app.appspot.com',
    iosClientId: '453651186731-5su07iiff1osu79s0bnfl1d869gjq7f9.apps.googleusercontent.com',
    iosBundleId: 'in.ryzntx.cashier.kasirApp',
  );
}
